In [2]:
import pandas as pd
import numpy as np
import chunk
import re
from datetime import datetime

#pd.set_option('display.max_columns',30)

In [ ]:
y12=pd.read_csv('C://Users//Owner//DA//Classwork//0 Activities//Final_Project//Final Cuts//desmoines//cleany12.csv')
y13=pd.read_csv('C://Users//Owner//DA//Classwork//0 Activities//Final_Project//Final Cuts//desmoines//cleany13.csv')
y14=pd.read_csv('C://Users//Owner//DA//Classwork//0 Activities//Final_Project//Final Cuts//desmoines//cleany14.csv')
y15=pd.read_csv('C://Users//Owner//DA//Classwork//0 Activities//Final_Project//Final Cuts//desmoines//cleany15.csv')
y16=pd.read_csv('C://Users//Owner//DA//Classwork//0 Activities//Final_Project//Final Cuts//desmoines//cleany16.csv')
y17=pd.read_csv('C://Users//Owner//DA//Classwork//0 Activities//Final_Project//Final Cuts//desmoines//cleany17.csv')

# To do: clear the 10,10,10 in y12, evaluate the county/county# in y16, and the cat/catname in y17

In [3]:
y12=pd.read_csv('C://Users//Owner//DA//Classwork//0 Activities//Final_Project//Final Cuts//desmoines//cleany12.csv')
ytest12=y12

In [5]:
y12[y12['State Bottle Cost'].isna()]['Item Number'].unique()

array([38180, 35920], dtype=int64)

In [6]:
y12[y12['State Bottle Cost'].isna()]['Item Description'].unique()

array(['Titos Handmade Mini', 'Pearl Wedding Cake Vodka Mini'],
      dtype=object)

In [8]:
y12[y12['Item Description']=='Titos Handmade Mini']['State Bottle Cost'].unique()

array(['$10.03', nan], dtype=object)

In [9]:
y12[y12['Item Description']=='Pearl Wedding Cake Vodka Mini']['State Bottle Cost'].unique()

array(['$5.00', nan], dtype=object)

In [ ]:
State Bottle Cost        10
State Bottle Retail      10
Bottles Sold              0
Sale (Dollars)           10

In [15]:
print(y12[y12['Item Description']=='Titos Handmade Mini']['State Bottle Retail'].unique()
,'and',
y12[y12['Item Description']=='Pearl Wedding Cake Vodka Mini']['State Bottle Retail'].unique())

['$15.05' nan] and ['$7.50' nan]


In [18]:
y12[y12['Item Description']=='Pearl Wedding Cake Vodka Mini']['Sale (Dollars)'].unique()

array(['$30.00', '$7.50', '$180.00', '$90.00', '$45.00', '$15.00',
       '$450.00', '$22.50', nan, '$360.00', '$37.50'], dtype=object)

In [19]:
y12[y12['Sale (Dollars)'].isna()]['Store Number'].unique()

array([3583, 2190, 2614, 2593, 2616, 4509, 2549, 2629, 2623], dtype=int64)

In [19]:
y12[y12['Sale (Dollars)'].isna()]['Store Number'].unique()

array([3583, 2190, 2614, 2593, 2616, 4509, 2549, 2629, 2623], dtype=int64)

In [26]:
c = [3583, 2190, 2614, 2593, 2616, 4509, 2549, 2629, 2623]
for i in c:
    while y12[y12['Store Number']]== i:
              y12[y12['Item Description']=='Pearl Wedding Cake Vodka Mini']['Sale (Dollars)'].unique()

KeyError: "None of [Int64Index([2459, 2487, 4509, 2522, 3816, 3912, 3540, 3819, 4344, 4105,\n            ...\n            2576, 4255, 2528, 2650, 3651, 4386, 2806, 2510, 2500, 3842],\n           dtype='int64', length=2082059)] are in the [columns]"